# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created: Wed Mar 04 15:46:17 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1058, 617)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabMain = QtGui.QTabWidget(self.centralwidget)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.cbSuperstrate = QtGui.QComboBox(self.tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbSuperstrate.setFont(font)
        self.cbSuperstrate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbSuperstrate.setStyleSheet(_fromUtf8("text-align: right;"))
        self.cbSuperstrate.setEditable(True)
        self.cbSuperstrate.setObjectName(_fromUtf8("cbSuperstrate"))
        self.cbSuperstrate.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cbSuperstrate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tblStack = QtGui.QTableWidget(self.tab)
        self.tblStack.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblStack.setAlternatingRowColors(True)
        self.tblStack.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblStack.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblStack.setObjectName(_fromUtf8("tblStack"))
        self.tblStack.setColumnCount(2)
        self.tblStack.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.tblStack.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblStack.setItem(4, 1, item)
        self.tblStack.horizontalHeader().setSortIndicatorShown(False)
        self.tblStack.horizontalHeader().setStretchLastSection(True)
        self.tblStack.verticalHeader().setVisible(True)
        self.verticalLayout_3.addWidget(self.tblStack)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnAddLayer = QtGui.QPushButton(self.tab)
        self.btnAddLayer.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/list-add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddLayer.setIcon(icon)
        self.btnAddLayer.setObjectName(_fromUtf8("btnAddLayer"))
        self.horizontalLayout_7.addWidget(self.btnAddLayer)
        self.btnRemoveLayer = QtGui.QPushButton(self.tab)
        self.btnRemoveLayer.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/list-remove.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoveLayer.setIcon(icon1)
        self.btnRemoveLayer.setObjectName(_fromUtf8("btnRemoveLayer"))
        self.horizontalLayout_7.addWidget(self.btnRemoveLayer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.cbSubstrate = QtGui.QComboBox(self.tab)
        self.cbSubstrate.setEditable(True)
        self.cbSubstrate.setObjectName(_fromUtf8("cbSubstrate"))
        self.cbSubstrate.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.cbSubstrate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.tabMain.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabMain.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabMain)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pltMain = MatplotlibWidget(self.centralwidget)
        self.pltMain.setObjectName(_fromUtf8("pltMain"))
        self.verticalLayout.addWidget(self.pltMain)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnUpdate = QtGui.QPushButton(self.centralwidget)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.horizontalLayout.addWidget(self.btnUpdate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlot = QtGui.QMenu(self.menubar)
        self.menuPlot.setObjectName(_fromUtf8("menuPlot"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuPlot.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Superstrate", None))
        self.cbSuperstrate.setItemText(0, _translate("MainWindow", "1.0", None))
        item = self.tblStack.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tblStack.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tblStack.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tblStack.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tblStack.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.tblStack.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Thickness (nm)", None))
        item = self.tblStack.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Index", None))
        __sortingEnabled = self.tblStack.isSortingEnabled()
        self.tblStack.setSortingEnabled(False)
        item = self.tblStack.item(0, 0)
        item.setText(_translate("MainWindow", "266", None))
        item = self.tblStack.item(0, 1)
        item.setText(_translate("MainWindow", "2.2", None))
        item = self.tblStack.item(1, 0)
        item.setText(_translate("MainWindow", "145", None))
        item = self.tblStack.item(1, 1)
        item.setText(_translate("MainWindow", "1.5", None))
        item = self.tblStack.item(2, 0)
        item.setText(_translate("MainWindow", "266", None))
        item = self.tblStack.item(2, 1)
        item.setText(_translate("MainWindow", "2.2", None))
        item = self.tblStack.item(3, 0)
        item.setText(_translate("MainWindow", "145", None))
        item = self.tblStack.item(3, 1)
        item.setText(_translate("MainWindow", "1.5", None))
        item = self.tblStack.item(4, 0)
        item.setText(_translate("MainWindow", "266", None))
        item = self.tblStack.item(4, 1)
        item.setText(_translate("MainWindow", "2.2", None))
        self.tblStack.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Substrate", None))
        self.cbSubstrate.setItemText(0, _translate("MainWindow", "1.45", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab), _translate("MainWindow", "Stack", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_2), _translate("MainWindow", "Plot", None))
        self.btnUpdate.setText(_translate("MainWindow", "Update", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionSave.setText(_translate("MainWindow", "Save...", None))
        self.actionOpen.setText(_translate("MainWindow", "Open...", None))
        self.actionExport.setText(_translate("MainWindow", "Export...", None))

from matplotlibwidget import MatplotlibWidget
